### ISSUE TITLE
Image expand issue 

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#33]
From MS Today: When you click on the image on the right side of the new template it goes to the top of the screen and you can't minimize or close out of it. 

@ben Is this the same Largo version issue we're seeing elsewhere, or something different?

**Comment by benlk** [comment]
Looks like it. I'll create a Largo issue for that, because it doesn't look like we have one yet.

<img width="1030" alt="Screen Shot 2019-04-15 at 16 40 26 " src="https://user-images.githubusercontent.com/1754187/56163774-30846d00-5f9d-11e9-988c-91177dd6ed28.png">

**Comment by benlk** [comment]
https://github.com/INN/largo/issues/1664

**Comment by benlk** [comment]
This should now be fixed in 0.6.3.

I have attempted to deploy a fix to this on staging, but experienced a problem with WPE's environment where the deployed Largo submodule was not updated.

**Comment by benlk** [comment]
Deployed that by hand.
