### ISSUE TITLE
Post prominences not saving; SiteOrigin PageBuilder bug

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#34]
From MS Today: 

"I created another test post to see how the new template will work with the PageBuilder plugin we use to customize story posts and pages beyond the limits of the Gutenberg editor. Even though I set the post prominence to “Exclude from Homepage,” the post is showing up really big on the homepage."

**Comment by MirandaEcho** [comment]
@benlk  what are your thoughts?  If this is an issue due to the page builder plugin it might be out of scope.

**Comment by benlk** [comment]
<img width="1030" alt="Screen Shot 2019-04-15 at 16 05 04 " src="https://user-images.githubusercontent.com/1754187/56161723-42174600-5f98-11e9-9c0a-0c69015191d1.png">

Normally, Largo's homepage displays the excerpt of the post, or the first few sentences of that post. I thought that this was a case of the first few sentences being displayed, but that is not the case: The post's excerpt is set and so it should be displayed. 

https://github.com/INN/largo/blob/099fd2c9361b7a4e9e6e729d35adde40685cb0fb/inc/post-tags.php#L206-L208

Note that Largo allows filtering of the excerpt using the standard WordPress filter.

In the SiteBuilder plugin, there's a function that overrides the default excerpt with their custom excerpt generation behavior, `SiteOrigin_Panels::generate_post_excerpt`. This function's output is responsible for the display seen here.

**Comment by benlk** [comment]
There are two options to change what's happening with that post:

1. Not use PageBuilder to compose posts. (not likely)
2. Make sure that the first two rows of a PageBuilder post contain at least one text-type widget, from which the excerpt can be drawn.

We can report this bug to SiteOrigin for them.

**Comment by benlk** [comment]
As for why the post with the "Exclude from homepage" term isn't being excluded, that appears to be because "Exclude from homepage" was not saved. That appears to be a problem between Largo and Gutenberg, which will be fixed in the next version of Largo with https://github.com/INN/largo/pull/1655. Until we upgrade them to the latest Largo, they'll need to check prominence terms in *both* post prominence boxes in the post editor.

**Comment by MirandaEcho** [comment]
Closing after communicating the details to MS Today.
