### ISSUE TITLE
CSS change for font kerning

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#36]
"CSS property to use for adjusting the kerning: https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing I don't know what units the "20" that Lauchlin gave were in, but we can eyeball that.

For CSS, up to an hour including staging deploys, but call it two because I"m sure we'll get a change request from them."

More Info: https://secure.helpscout.net/conversation/818612984/3510?folderId=2771512

**Comment by MirandaEcho** [comment]
@josh please increase to 0.3

**Comment by joshdarby** [comment]
@MirandaEcho This has been deployed to staging. 

http://mstoday.staging.wpengine.com/2019/03/08/tax-collections-strong-in-final-report-before-decision-on-teacher-state-employee-pay-hike/

**Comment by MirandaEcho** [comment]
@josh they want to try switching the font altogether to "Georgia".  They have approved extra time for this (1 hour).

**Comment by joshdarby** [comment]
@MirandaEcho This has been deployed to their staging environment.

**Comment by joshdarby** [comment]
@MirandaEcho Can we close this?
