### ISSUE TITLE
Author tracking - GMT and GA code settings

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#37]
"Thanks, Ben. I have done some testing on staging, but, I'm unsure how to test the GTM and GA codes and settings in staging, since the site doesn't allow search engines to index. Maybe I'm missing something? It looks like the DuracellTomi's plugin still requires adding the GTM code in the header and footer, so I'm not sure how to do both (since you said that plugin won't work with the Insert Headers and Footers plugin). I don't want to have another instance of losing valuable GA data from our live site, which is why I'm a little hesitant to go through all of the necessary steps."

It looks like what we'd need to do here is: 
- On staging, Remove Insert Headers and Footers (5m)
- On staging, Install DuracellTomi's plugin (5m) and configure (5m)
- Coordinate time with client to make the change on production (?)
- redo those plugin changes on production (15m + 10m backup)

More info: https://secure.helpscout.net/conversation/818612984/3510?folderId=2771512

**Comment by joshdarby** [comment]
@MirandaEcho All of the steps for the staging site have been completed.

**Comment by MirandaEcho** [comment]
@josh 

Lauchlin says: "I granted Josh access to GA and GTM, so he can make sure everything is set to fire properly and collect author tracking. If you could launch the changes to the live site early in the morning and let me know when it's done, that would be great. I'll be sure to check early. Sorry for my delay getting back to you on all this. I appreciate you taking care of all this!"

If you happen to see this before tomorrow morning, otherwise we'll figure out a different time.

**Comment by joshdarby** [comment]
@MirandaEcho I have this working on their staging environment. If they go into Analytics and add "Post Author" as a secondary dimension they should be able to see it working on the few posts I tested it on.

**Comment by joshdarby** [comment]
@MirandaEcho This has been deployed to production.

- Insert Headers and Footers plugin deactived
- DuracellTomi's Google Tag Manager plugin installed, activated, and configured
- Google Tag Manager analytics tag updated to push `Post Author` data to GA `Dimension 2`

**Comment by joshdarby** [comment]
@MirandaEcho Can we close this?
