### ISSUE TITLE
Add LinkedIn Share Button

### ISSUE THREAD

**Issue by julia67** [INN/umbrella-mstoday#4]
HelpScout #1575

See The Rivard Report for an example: 
- https://github.com/INN/umbrella-rivard-report/blob/master/wp-content/themes/rivard-report/inc/post-tags.php#L6-L44
- https://therivardreport.com/wolff-to-endorse-austins-kopser-in-district-21-congressional-race/

**Comment by benlk** [comment]
Resolved with #9 and #10, and deployed with #11.
