### ISSUE TITLE
Add byline and author back in to blank Gutenberg template

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#41]
We removed them when we created the template, but they do want them included.  If this is just a setting in Gutenberg or something let me know, otherwise, please add them back in to the template. If its going to take longer than ~30 min let me know.

**Comment by benlk** [comment]
In https://github.com/INN/umbrella-mstoday/blob/master/wp-content/themes/mstoday/partials/content-blank.php, add the largo_byline call inside a `<header>` element, like in Largo's partials/content-single.php

https://github.com/INN/largo/blob/d0db10df71c22777b8051675bb854f24d98ee3d2/partials/content-single.php#L19

**Comment by joshdarby** [comment]
@MirandaEcho This has been deployed to their staging environment. Do you know if they have a specific post they want to double check this on? If not, they (or us) can just create a sample post on the staging environment to make sure it looks good to them.

**Comment by MirandaEcho** [comment]
@josh "Can we please have the byline and dateline go below the photo? Would there ever be an option for us to decide case-by-case where the byline appears? Maybe even have the option of it appearing on top of the photo like this: https://www.clarionledger.com/story/news/politics/2017/09/24/hunger-food-desert-mississippi-delta-impacts-health/588052001/? Just wondering if there is any wiggle room there. I’m sure to have it on the photo is another project down the road. If we can’t decide where ti goes on each post, we definitely want it to go below the featured/lead image." - 1 hr approved for this, lets discuss options.

**Comment by joshdarby** [comment]
@MirandaEcho Building out a UI that allows them to select where it can go on a case by case basis would take longer than an hour with building the ui and building out the styles for each specific case.
