### ISSUE TITLE
Disappearing photo captions

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#47]
CAPTION ISSUES: Any photo that is full screen (and in the case of mobile, one smaller than full screen), the photo captions cut off on either side. Additionally, the caption text for one photo is different from the caption text in a photo gallery (not as big of an issue). I’m using chrome but I don’t know that it matters what version of Windows it is. It cuts off on both me and Alex’s comps, plus mobile.

I can’t recreate the caption issue on a live story because when I put the photo in full size, it pushes to the left side of the page now, as attached. 
![example](https://user-images.githubusercontent.com/48263361/58723684-5bd1e880-83a0-11e9-8ea2-153e9fc5c45a.png)

Same on mobile. Before, it was cutting off just a sliver of the text on either side of the photo. I tried to recreate this in the preview version of the dollar general story and the example of that is attached. 
![example2](https://user-images.githubusercontent.com/48263361/58723734-6ee4b880-83a0-11e9-8a51-576cf90b7c5a.png)

This is the primary issue I’m talking about. See how “Left” is cut off on the left side of the image. This is why we don’t have any fullsize images on our site right now (save for the lede images on the longform template, which doesn’t have a caption so it doesn’t matter).

Mobile screenshot:
![image1](https://user-images.githubusercontent.com/48263361/58723772-8623a600-83a0-11e9-802f-33f407d5064e.png)

I’m using Windows 7 Professional, browser Chrome. This is what all MS today reporters have, I believe.

**Comment by MirandaEcho** [comment]
@joshdarby we've estimated an hour to look into this, so be aware and let me know if more info is needed or if its a larger issue. Thanks!

**Comment by benlk** [comment]
This looks like it's having trouble with the alignment on alignfull images. https://mississippitoday.org/2019/05/15/living-day-to-day-surrounded-by-water-and-ignored-by-powerful-officials-tchula-and-its-people-fight-for-survival/ now uses alignwide.

**Comment by benlk** [comment]
Using a fullwidth image on the Blank Page template, I am unable to reproduce this in the current version of Chrome on OSX

@MirandaEcho Next steps: 

- what version of Chrome is being used in the screenshot? Click the three-dot menu in the upper-left of the browser, then "help", then "about Google Chrome", or go to `chrome://settings/help` in the URL bar.
