### ISSUE TITLE
Photo galleries on iOS aren't displaying correctly, slick slider is set to default - why?

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#48]
Lead photo issue on Mobile - we can investigate this further to see why the slick slider is set to the default gallery and why the width isn't correct on mobile.

**Comment by joshdarby** [comment]
As to why it's set to slick slider, I believe it's coming from using the `gallery` shortcode. If you use the default gutenberg gallery block, it uses the correct navis slideshow gallery.

**Comment by MirandaEcho** [comment]
Recommended trying a different slider plugin
