### ISSUE TITLE
Adding elements back into longform template

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#49]
Add the following page elements back into the blank longform template:
- [x] Author and bio section at bottom
- [x] "Filed Under" section
- [x] Scrolling share buttons on left side of screen

They do not want comments or "read next".

**Comment by joshdarby** [comment]
Merged into staging in PR #50.

**Comment by benlk** [comment]
Deployed; visible at https://mississippitoday.org/2019/02/18/after-years-of-inaction-delta-teacher-shortage-reaches-crisis-levels/

**Comment by benlk** [comment]
The social media buttons are appearing at the top of the production pages, and the floating social buttons are in a different place:

Prod:
<img width="1525" alt="Screen Shot 2019-06-11 at 20 39 38 " src="https://user-images.githubusercontent.com/1754187/59315746-13140c80-8c89-11e9-9ea7-951722c21d6b.png">

Staging:
<img width="1525" alt="Screen Shot 2019-06-11 at 20 39 46 " src="https://user-images.githubusercontent.com/1754187/59315754-18715700-8c89-11e9-9c22-3458d6ebc281.png">

But as far as I can tell, they're both checked out at the same commit for `HEAD`?

```
$ git ls-remote wpe-staging 
8decca89b88795b015092f777663ba8f2e6b1f1c	HEAD
16d22db70b918afe70250ac75c31f23d8604cd48	refs/heads/24-homepage-top-story
12f2db77e007d4e022cb5bbca571bfaf9b5454ec	refs/heads/28-new-template
8decca89b88795b015092f777663ba8f2e6b1f1c	refs/heads/master
d0aff364d8f3de5d2d523e268b478d4029619ea4	refs/heads/staging
$ git ls-remote wpe-prod
8decca89b88795b015092f777663ba8f2e6b1f1c	HEAD
8decca89b88795b015092f777663ba8f2e6b1f1c	refs/heads/master
```

**Comment by benlk** [comment]
It was goshdanged cached CSS on the production site. Adding a cachebuster in https://github.com/INN/umbrella-mstoday/commit/9038386d4ab707e8cce38217e6e1a6e6327c76a0 fixed the problem in prod.
