### ISSUE TITLE
Add option to hide thumbnail images on mobile homepage

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-mstoday#5]
The option to should allow users to keep the mobile thumbnail on some stories.

*Use case:* Mississippi Today editors want to make sure headlines aren't buried too far down the homepage and need an option to hide the the thumbnail image on featured stories:

![screencapture-mississippitoday-org-1518019617515](https://user-images.githubusercontent.com/1643734/35927257-df6ee12c-0bef-11e8-8c15-def2a9cfe0a9.jpg)

That option should be added to the Featured Media metabox on the Post Edit screen, like so:
![screen-shot-2018-02-07-at-10 14 34-am](https://user-images.githubusercontent.com/1643734/35927439-52a6cf88-0bf0-11e8-8e3b-f6ac9f95b78e.jpg)

**Comment by benlk** [comment]
Does this have to be a featured media meta box? What would be faster would be:

1. Create a prominence term like "Hide featured media on homepage" with slug `homepage-hide-slug`, via the Dashboard
2. Create styles in the homepage less/css targeting `.home .prominence-homepage-hide-slug` or whatever the class output via largo's `post_class` filter is called, which hide the image:

```
.home .prominence-hide-slug {
    header {
        display: none;
    }
}
```

3. recompile LESS
4. After deploying, create the prominence term on staging/production

**Comment by julia67** [comment]
@benlk that sounds great. Proceed with the prominence term solution. Thanks!
