### ISSUE TITLE
Add option to relocate the second lead art area on mobile

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-mstoday#6]
For this section:
![screencapture-mississippitoday-org-1518019617515-2](https://user-images.githubusercontent.com/1643734/35929048-31e4c9ea-0bf4-11e8-9347-6207c2c67eb7.jpg)

Add two more options for the photo layout, as seen below. This could be handled by an alternate homepage template, potentially.

Image aligned left:
<img width="398" alt="screen shot 2018-02-07 at 10 34 56 am" src="https://user-images.githubusercontent.com/1643734/35928948-01e9cdda-0bf4-11e8-9228-91d88b7e5256.png">

```
@media only screen and (max-width: 500px) {
    .homepage-top-rail-left h2 {
        width: 65%;
        float: left;
    }
    .homepage-top-rail-left .hero {
        width: 30%;
        margin: 0 5%;
    }
    .home .homepage-top-rail-left .entry-content .entry-title {
        font-size: 1.5em;
    }
}
```

Image aligned right:
<img width="394" alt="screen shot 2018-02-07 at 10 36 01 am" src="https://user-images.githubusercontent.com/1643734/35928976-0c91f3fc-0bf4-11e8-9e50-549aeed31f6a.png">

```
@media only screen and (max-width: 500px) {
    .homepage-top-rail-left h2 {
        width: 65%;
        float: left;
    }
    .homepage-top-rail-left .hero {
        width: 30%;
        margin: 0 0 0 5%;
        float: right;
    }
    .home .homepage-top-rail-left .entry-content .entry-title {
        font-size: 1.5em;
    }
}
```

**Comment by benlk** [comment]
Notes from pairing with Kay:

Extending the existing homepage layout class to have two separate layouts that exist only for a little bit of CSS seems a bit overkill. Is that really the best way to handle this?

Questions:
- Should the layout be stored at the post level, or should is this supposed to apply to all posts that fall in that spot during the time that the homepage layout is changed?
- Will there ever be a case where they want the full image back? Can we just maintain one template that chooses smaller-and-left or smaller-and-right?

**Comment by benlk** [comment]
Notes from convo with Julia:

- Don't tie it to a post, just do different homepage layouts
- Or https://github.com/INN/developer-driven-custom-post-classes, output a post class there that hides the image, define classes like how we did in Chicago Reporter with the theme tie-in filter.
