### ISSUE TITLE
Add subscribe button next to donate button on the homepage, ensure it displays on mobile

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#66]
Background:

On mobile, we hope to move a subscribe button “above the fold.” Currently on mobile navigation, a user has to navigate under the more tab to find our newsletter page.
Need help from INN to add a subscribe button next to the donate button on the homepage.

**Comment by joshdarby** [comment]
@MirandaEcho I'm a little confused. This issue says to add it on the homepage, but in the background comment they mention it's currently in the navigation. Are they talking about adding it next to the donate button in the top nav like here
![Screen Shot 2020-03-03 at 9 49 09 AM](https://user-images.githubusercontent.com/18353636/75787227-6573ec80-5d34-11ea-8096-73f9786ede69.png)

![Screen Shot 2020-03-03 at 9 49 23 AM](https://user-images.githubusercontent.com/18353636/75787220-63119280-5d34-11ea-8198-84d5258f5e4c.png)

Or are they wanting it added here?
![Screen Shot 2020-03-03 at 9 50 28 AM](https://user-images.githubusercontent.com/18353636/75787275-76bcf900-5d34-11ea-8c2d-0f30eba85810.png)

**Comment by joshdarby** [comment]
From Lauchlin:

>We want a button similar to the "Donate" button that appears at the top of the page (between the social media buttons and search bar on desktop and in the nav menu on mobile). Is it possible for that button to have a different color (maybe #B92454?) so it stands out next to the Donate button?
