### ISSUE TITLE
Custom widget for inserting single post in sidebars

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#72]
Create a custom widget so they can insert a specific post in their sidebar. It should match the styling of the recent/related posts.

**Comment by MirandaEcho** [comment]
From the estimate: We could quickly spin up a custom widget for you that allows you to insert a single post with the same styling that the recent posts widget uses.  This would take less than 4 hours, and we could get it done for you in the next day or two.

**Comment by benlk** [comment]
Putting in a shim for https://github.com/INN/largo/issues/1855 while I'm in here.
