### ISSUE TITLE
Reduce H1 heading size by half on mobile for the blank Gutenberg template

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#75]
"I'd like the ability to change the headline size on mobile when using the block editor/longform template. I like the current h1 size on desktop. I just need it smaller on mobile. "

Confirmed hard coded is fine, start with half size and we'll see how that looks.

**Comment by joshdarby** [comment]
> the block editor/longform template

Do we know what template she's referring to here? Here's a list of the available post templates:
![Screen Shot 2020-05-22 at 9 14 08 AM](https://user-images.githubusercontent.com/18353636/82671338-adf0c700-9c0c-11ea-99a9-065d94bb11e6.png)

**Comment by MirandaEcho** [comment]
Blank Page (MS Today special) is the custom template we made them for Gutenberg articles.

**Comment by joshdarby** [comment]
The current H1 size is 64px. Half of that would be 32px.

However, the current H2 size is 36px so it would be 4px bigger than the H1 on mobile. @MirandaEcho should we set the H1 to 38px?

**Comment by MirandaEcho** [comment]
@joshdarby yes that makes sense. Thanks!
