### ISSUE TITLE
Quick pagespeed analysis/recommendations

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#77]
Pagespeed scores for the site are coming in VERY low. Let's take a look and create a short list of recommendations.

**Comment by joshdarby** [comment]
It looks like the main things Google is complaining about is deferring offscreen images (16.23s), serving images in next-gen formats (13.98s), and eliminating render-blocking resources (12.41s), reduce third-party code blocking main thread

What we can do:
- Install autoptimize
   - enable lazy-loading
   - enable serving images in WebP format
   - play around with CSS caching/optimization to fix the render-blocking issue
   - minify JS
- Remove any third party scripts that aren't needed that are taking up lots of bandwith
- Remove any unused plugins
- Help them figure out a solution to using or not using Cloudflare as their CDN

Link to report: https://developers.google.com/speed/pagespeed/insights/?url=mississippitoday.org

![screencapture-developers-google-speed-pagespeed-insights-2020-05-22-09_51_38](https://user-images.githubusercontent.com/18353636/82674801-da5b1200-9c11-11ea-9bab-c808acd16e00.png)
