### ISSUE TITLE
Custom page and post templates for cultural coverage

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#89]
Design details still needed, but we can start with the template setup and creation.

**Comment by joshdarby** [comment]
@MirandaEcho Is "cultural coverage" supposed to be a new post type, or just a new template that they can use?

Also, is the 2 hours here just for the setup or for the design implementation as well?

**Comment by MirandaEcho** [comment]
Good question!

Estimate is just for the setup until we get more details, don't worry!

"Create new custom page and post template for cultural coverage that can be hidden from the homepage with custom post type"

**Comment by joshdarby** [comment]
> Create new custom page and post template for cultural coverage that can be hidden from the homepage with custom post type

@MirandaEcho I'm still confused here. Is it going to be just a custom template or a custom template + custom post type?
